spring.application.name=codymitra-service
server.servlet.context-path=/api
server.port=8060
server.address=0.0.0.0
spring.localUrl=http://locahost:


spring.datasource.url=jdbc:postgresql://localhost:5432/account_erp
spring.datasource.username=primesysindia
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false




# jwt properties
jwt.secret=b7790e23dfec38d707783c9a3a21b851834f12093dff8141150277c674c11944
jwt.access-expiration=604800000
jwt.refresh-expiration=1604800000