spring.application.name=codymitra-service
server.servlet.context-path=/api
server.port=8060


spring.datasource.url=jdbc:postgresql://localhost:5432/account_erp
spring.datasource.username=primesysindia
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false